#!/usr/bin/env bash

# script to deploy a new VHOST to multihost
# m.opitz@qmul.ac.uk | 2017-11-20

echo v.1.2

usage() { echo "Usage: $0 <servername>" 1>&2; exit 1; }

if [ ! $1 ]
	then
	usage
fi

# check for the config file and get the settings
if [ ! -f /etc/multihost.conf ]
	then
	echo No configuration file found at /etc/multihost.conf file found - aborting!
	exit 1
fi
. /etc/multihost.conf

servername=$1

if [ -f ${sites_enabled_path}/${servername}.conf ]
	then
	echo A server with the name ${servername} already exists - aborting!
	exit 1
fi

if [ ! -d ${www_path}/${servername} ]
	then
	echo No webroot folder found at ${www_path}/${servername} - aborting!
	exit 1
fi

if [ ! -f ${sites_enabled_path}/default.configuration ]
	then
	echo "Could not find a ${sites_enabled_path}/default.configuration file - aborting!"
	exit 1
fi

cp ${sites_enabled_path}/default.configuration ${sites_enabled_path}/${servername}.conf
sed -i "s/TheServerName/${servername}/g" ${sites_enabled_path}/${servername}.conf
chmod 777 ${sites_enabled_path}/${servername}.conf
if [ -d ${moodledata_path}/${servername} ]
	then
	sudo rm -r ${moodledata_path}/${servername}
fi
mkdir ${moodledata_path}/${servername}
chmod -R 777 ${moodledata_path}/${servername}
ln -s ${filedir_path} ${moodledata_path}/${servername}/filedir

restart_multihost

echo "VHOST ${servername} configured and activated - please add ${servername} to your local /etc/hosts file"

