#!/usr/bin/env bash

# script to run an Apache instance with external config using Docker image with centos7 / Apache / PHP 
# m.opitz@qmul.ac.uk | 2017-11-20

echo v.2.6
# v.2.1 - added hostmane to container
# v.2.2 - now removing all other multihost container when starting a new one and serving php5.6 over 80 / 443
# v.2.3 - now using setup details  to make changes easier
# v.2.4 - now reading setup details from /etc/multihost.conf and creating reboot_multihost command script
# v.2.5 - renamed reboot_multihost to restart_multihost
# v.2.6 - installing scripts into /usr/local/bin instead of /usr/sbin

usage() { echo "Usage: $0 [-o<c/u>] [-p<7/5>]" 1>&2; exit 1; }

# check for the config file and get the settings
if [ ! -f /etc/multihost.conf ]
        then
        echo No configuration file found at /etc/multihost.conf file found - aborting!
        exit 1
fi
. /etc/multihost.conf

while getopts ":p:o:" x; do
    case "${x}" in
        o)
            o=${OPTARG}
            ;;
        p)
            p=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ "${p}" == "5" ]
	then
	php_v=56
	port=80
	ssl_port=443
else
	php_v=7
	port=80
	ssl_port=443
fi

# remove any exsiting multihost container, running or not
docker rm -f multihost_centos7_php7_httpd >/dev/null 2>/dev/null
docker rm -f multihost_centos7_php56_httpd >/dev/null 2>/dev/null
docker rm -f multihost_ubuntu_php7_apache2 >/dev/null 2>/dev/null
docker rm -f multihost_ubuntu_php56_apache2 >/dev/null 2>/dev/null


if [ "${o}" == "u" ]
	then
	os=ubuntu_php${php_v}_apache2
	conf_path=/etc/apache2/sites-enabled
	servername=multihost_${os}

#	docker rm -f ${servername} >/dev/null 2>/dev/null
	docker run -itd \
		--name ${servername} \
		-h ${servername} \
		-p ${port}:80 \
		-p ${ssl_port}:443 \
		-v ${sites_enabled_path}:${conf_path} \
		-v ${www_path}:/var/www \
		-v ${moodledata_path}:/var/moodledata \
		-v ${filedir_path}:/filedir \
		-v ${xchange_path}:/xchange \
		--add-host db_host:${db_host_ip} \
		${os}
	docker exec ${servername} service apache2 restart
	echo "docker exec ${servername} service apache2 restart">/usr/local/bin/restart_multihost
else
	os=centos7_php${php_v}_httpd
	conf_path=/etc/httpd/sites-enabled
	servername=multihost_${os}

#	docker rm -f ${servername} >/dev/null 2>/dev/null
	docker run -itd \
		--privileged=true \
		--name ${servername} \
		-h ${servername} \
		-p ${port}:80 \
		-p ${ssl_port}:443 \
		-v /sys/fs/cgroup:/sys/fs/cgroup:ro \
		-v ${sites_enabled_path}:${conf_path} \
		-v ${www_path}:/var/www \
		-v ${moodledata_path}:/var/moodledata \
		-v ${filedir_path}:/filedir \
		-v ${xchange_path}:/xchange \
		--add-host db_host:${db_host_ip} \
		${os}
	docker exec ${servername} systemctl restart httpd
	echo "docker exec ${servername} systemctl restart httpd">/usr/local/bin/restart_multihost
fi

echo now running ${servername}
