#!/usr/bin/env bash

# script to disable a VHOST on Dcoker multihost
# m.opitz@qmul.ac.uk | 2018-02-16
if [[ $EUID -ne 0 ]]; then
   echo "SORRY! This script must be run as root/superuser!" 
   exit 1
fi

echo ' '
echo "Docker multihost disable VHOST v.1.5"
echo "-------------------------------------"

usage() { echo "Usage: $0 <servername>" 1>&2; exit 1; }

if [ ! $1 ]
	then
	usage
fi

# check for the config file and get the settings
if [ ! -f /etc/multihost.conf ]
	then
	echo No configuration file found at /etc/multihost.conf file found - aborting!
	exit 1
fi
. /etc/multihost.conf

servername=$1

if [ ! -f ${sites_enabled_path}/${servername}.conf ]
	then
	echo "--> Could not find ${sites_enabled_path}/${servername}.conf - skipping!"
else
	sudo rm ${sites_enabled_path}/${servername}.conf >/dev/null 2>/dev/null
	echo "--> ${sites_enabled_path}/${servername}.conf has been removed."
fi

if [ ! -d ${moodledata_path}/${servername} ]
	then
	echo "--> Could not find ${moodledata_path}/${servername} - skipping!"
else
	sudo rm -r ${moodledata_path}/${servername} >/dev/null 2>/dev/null
	echo "--> ${moodledata_path}/${servername} has been removed."
fi

# remove symlink from within the base webserver
rm -rf ${www_path}/html/${servername}

# remove server from moodle_crontab
if [ -f ${moodledata_path}/moodle_crontab ]
	then
	# remove the line(s) that contain "/the_servername/" from ${moodledata_path}/moodle/crontab
	if [ "`uname`" == "Darwin" ]
		then
		sed -i ' ' "/\/${servername}\//d" ${moodledata_path}/moodle_crontab
	else
		sed -i "/\/${servername}\//d" ${moodledata_path}/moodle_crontab
	fi
	echo "--> The crontab entry for ${servername} has been removed."
fi

restart_multihost

echo "--> VHOST ${servername} has been disabled on this server."
echo ' '
